spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: mysql://containers-us-west-171.railway.app:7080/railway
    username: root
    password: FtQFYVGpQTBfKSHVqJ9g
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: true
